server:
  port: 8500

  boot:
    admin:
      client:
        url: http://localhost:8508

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411/
