server:
  port: 8503

  boot:
    admin:
      client:
        url: http://localhost:8508

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: notification-service
  rabbitmq:
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: msqueue
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/


## burada input kullanmamizin sebebi kuyruk burada dinleme yapacagi icindir
