server:
  port: 8502

  boot:
    admin:
      client:
        url: http://localhost:8508

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: ticket-service
  rabbitmq:
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue
  datasource:
    url: jdbc:mysql://localhost:3306/ticket
    username: root
    password: ticket-app
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

## burada output kullanmamizin sebebi kuyruk burada yazma yapacagi icindir
